# Generated by Django 6.0.2 on 2026-05-02 12:58

import datetime
import django.utils.timezone
from django.db import migrations, models

from comun.claves import generate_secret_token


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailToken",
            fields=[
                (
                    "token",
                    models.CharField(
                        default=generate_secret_token,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=350)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_for", models.DurationField(default=datetime.timedelta(days=3))),
            ],
            options={
                "verbose_name": "token",
                "verbose_name_plural": "tokens",
                "ordering": ["created_at"],
            },
        ),
    ]
