# Generated by Django 6.0.2 on 2026-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id_familia', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_familia', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'familia',
                'verbose_name_plural': 'familias',
                'db_table': 'fam_familia',
                'ordering': ['id_familia'],
            },
        ),
    ]
