# Generated by Django 6.0.2 on 2026-04-10 20:26

from django.db import migrations

do_statements = [
    """
    INSERT INTO fam_familia (id_familia,nombre_familia) VALUES
	 ('F01','Autorizaciones, licencias, permisos, comunicaciones previas y declaraciones responsables'),
	 ('F02','Infracciones y sanciones'),
	 ('F03','Revisión de actos, recursos administrativos y reclamaciones previas'),
	 ('F04','Responsabilidad patrimonial'),
	 ('F05','Subvenciones, premios y becas'),
	 ('F06','Gestión de personal'),
	 ('F10','Certificaciones'),
	 ('F11','Registros administrativos'),
	 ('F12','Expropiación forzosa'),
	 ('F13','Gobierno y dirección'),
	 ('F14','Prestaciones sociales y sanitarias'),
	 ('F17','Sugerencias y reclamaciones'),
	 ('F19','Inspectora'),
	 ('UNK','Pendiente de definir'),
	 ('_NA','No aplicable');
     """
    ]

undo_statements = [
    "DELETE FROM fam_familia;",
    ]



class Migration(migrations.Migration):

    dependencies = [
        ("familias", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            do_statements,
            undo_statements,
            )
        ]
