# Generated by Django 5.2.4 on 2025-07-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Termino",
            fields=[
                ("id_termino", models.BigAutoField(primary_key=True, serialize=False)),
                ("entrada", models.CharField(max_length=128, unique=True)),
                ("descripcion", models.CharField(max_length=512)),
            ],
            options={
                "ordering": ["entrada"],
            },
        ),
    ]
