# Generated by Django 6.0.2 on 2026-02-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fuente",
            fields=[
                ("id_fuente", models.BigAutoField(primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=32, unique=True)),
                ("descripcion", models.TextField(max_length=512, unique=True)),
                ("url", models.URLField(blank=True, max_length=256)),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.CreateModel(
            name="Termino",
            fields=[
                ("id_termino", models.BigAutoField(primary_key=True, serialize=False)),
                ("entrada", models.CharField(max_length=128, unique=True)),
                ("descripcion", models.TextField(max_length=1024)),
                ("fuente", models.URLField(blank=True, default="", max_length=512)),
            ],
            options={
                "ordering": ["entrada"],
            },
        ),
    ]
