# Generated by Django 5.2.4 on 2025-07-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glosario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="termino",
            name="fuente",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="termino",
            name="descripcion",
            field=models.TextField(max_length=1024),
        ),
    ]
