# Generated by Django 5.2.4 on 2025-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glosario", "0002_termino_fuente_alter_termino_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fuente",
            fields=[
                ("id_fuente", models.BigAutoField(primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=32, unique=True)),
                ("descripcion", models.CharField(max_length=512, unique=True)),
                ("url", models.URLField(blank=True, max_length=256)),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
    ]
