# Generated by Django 5.2.4 on 2025-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glosario", "0003_fuente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuente",
            name="descripcion",
            field=models.TextField(max_length=512, unique=True),
        ),
    ]
