# Generated by Django 5.2.4 on 2025-08-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glosario", "0004_alter_fuente_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termino",
            name="fuente",
            field=models.URLField(blank=True, default="", max_length=512),
        ),
    ]
