# Generated by Django 6.0.2 on 2026-02-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rango",
            fields=[
                (
                    "id_rango",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("nombre_rango", models.CharField(max_length=32, unique=True)),
                ("peso", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Norma",
            fields=[
                ("id_norma", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_norma", models.TextField(max_length=620, unique=True)),
                ("sobrenombre", models.CharField(blank=True, max_length=32)),
                ("url", models.URLField(blank=True, max_length=320)),
                ("id_juriscan", models.IntegerField(default=0)),
                (
                    "es_generica",
                    models.BooleanField(
                        default=False,
                        help_text="Este norma es aplicable a todos los sistemas de información.",
                        verbose_name="La norma es de ámbito genérico",
                    ),
                ),
                (
                    "rango",
                    models.ForeignKey(
                        default="_na",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normas",
                        to="normativa.rango",
                    ),
                ),
            ],
        ),
    ]
