# Generated by Django 5.2.4 on 2025-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Norma",
            fields=[
                ("id_norma", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_norma", models.CharField(max_length=620, unique=True)),
                ("url", models.URLField(blank=True, max_length=320)),
                ("id_juriscan", models.IntegerField(default=0)),
            ],
        ),
    ]
