# Generated by Django 5.2.4 on 2025-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normativa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="norma",
            name="sobrenombre",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
