# Generated by Django 5.2.4 on 2025-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normativa", "0002_norma_sobrenombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="norma",
            name="nombre_norma",
            field=models.TextField(max_length=620, unique=True),
        ),
    ]
