# Generated by Django 5.2.4 on 2025-09-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normativa", "0003_alter_norma_nombre_norma"),
    ]

    operations = [
        migrations.AddField(
            model_name="norma",
            name="es_transversal",
            field=models.BooleanField(
                default=False,
                help_text="Este norma es aplicable a todos los sistemas de información.",
            ),
        ),
    ]
