# Generated by Django 5.2.4 on 2025-09-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normativa", "0004_norma_es_transversal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rango",
            fields=[
                (
                    "id_rango",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("nombre_rango", models.CharField(max_length=32, unique=True)),
                ("peso", models.IntegerField()),
            ],
        ),
    ]
