# Generated by Django 5.2.4 on 2025-09-01 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normativa", "0005_rango"),
    ]

    operations = [
        migrations.AddField(
            model_name="norma",
            name="rango",
            field=models.ForeignKey(
                default="_na",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="normas",
                to="normativa.rango",
            ),
        ),
    ]
