# Generated by Django 5.2.4 on 2025-09-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normativa", "0006_norma_rango"),
    ]

    operations = [
        migrations.AlterField(
            model_name="norma",
            name="es_transversal",
            field=models.BooleanField(
                default=False,
                help_text="Este norma es aplicable a todos los sistemas de información.",
                verbose_name="De ámbito genérico",
            ),
        ),
    ]
