# Generated by Django 5.2.4 on 2025-09-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("normativa", "0007_alter_norma_es_transversal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="norma",
            old_name="es_transversal",
            new_name="es_generica",
        ),
    ]
