# Generated by Django 5.2.4 on 2025-09-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normativa", "0008_rename_es_transversal_norma_es_generica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="norma",
            name="es_generica",
            field=models.BooleanField(
                default=False,
                help_text="Este norma es aplicable a todos los sistemas de información.",
                verbose_name="La norma es de ámbito genérico",
            ),
        ),
    ]
