# Generated by Django 5.2.8 on 2026-01-29 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Juriscan",
            fields=[
                (
                    "id_juriscan",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("titulo", models.CharField(max_length=2280)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("cheked", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["id_juriscan"],
            },
        ),
    ]
