# Generated by Django 6.0.2 on 2026-04-30 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juriscan',
            fields=[
                ('id_juriscan', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=2280)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Ficha Juriscán',
                'verbose_name_plural': 'Fichas de Juriscán',
                'ordering': ['id_juriscan'],
            },
        ),
    ]
