# Generated by Django 6.0.2 on 2026-02-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("juriscan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="juriscan",
            options={
                "ordering": ["id_juriscan"],
                "verbose_name": "Ficha Juriscán",
                "verbose_name_plural": "Fichas de Juriscán",
            },
        ),
    ]
