# Generated by Django 5.2.8 on 2026-01-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("juriscan", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="juriscan",
            old_name="cheked",
            new_name="checked",
        ),
    ]
