# Generated by Django 6.0.2 on 2026-02-23 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organismo",
            fields=[
                (
                    "id_organismo",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre_organismo", models.CharField(max_length=144, unique=True)),
                ("dir3", models.CharField(max_length=9, unique=True)),
                ("id_sirhus", models.IntegerField(unique=True)),
                ("categoria", models.CharField(max_length=40)),
                ("competencias", models.TextField(blank=True, default=None, null=True)),
                ("ruta", models.CharField(default="", max_length=128)),
                (
                    "url",
                    models.URLField(
                        blank=True, default=None, max_length=384, null=True
                    ),
                ),
                (
                    "f_alta",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha en la que el organismo se dio de alta",
                    ),
                ),
                (
                    "f_cambio",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de la última modificación del organismo",
                    ),
                ),
                ("f_baja", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "depende_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organismos_dependientes",
                        to="directorio.organismo",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre_organismo"],
            },
        ),
    ]
