# Generated by Django 6.0.2 on 2026-04-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=144, unique=True)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('f_alta', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que la empresa se dio de alta')),
                ('f_cambio', models.DateTimeField(auto_now=True, help_text='Fecha de la última modificación de la empresa')),
                ('f_baja', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Empresa externa',
                'verbose_name_plural': 'Empresas externas',
                'db_table': 'dir_empresa',
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id_organismo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_organismo', models.CharField(max_length=144, unique=True)),
                ('dir3', models.CharField(blank=True, max_length=9)),
                ('id_sirhus', models.IntegerField(blank=True)),
                ('categoria', models.CharField(max_length=40)),
                ('competencias', models.TextField(blank=True, default=None, null=True)),
                ('ruta', models.CharField(default='', max_length=128)),
                ('url', models.URLField(blank=True, default=None, max_length=384, null=True)),
                ('f_alta', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que el organismo se dio de alta')),
                ('f_cambio', models.DateTimeField(auto_now=True, help_text='Fecha de la última modificación del organismo')),
                ('f_baja', models.DateTimeField(blank=True, default=None, null=True)),
                ('depende_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organismos_dependientes', to='directorio.organismo')),
            ],
            options={
                'ordering': ['nombre_organismo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dir3', ''), _negated=True), fields=('dir3',), name='unique_dir3'), models.UniqueConstraint(condition=models.Q(('id_sirhus__isnull', True), _negated=True), fields=('id_sirhus',), name='unique_id_sirhus'), models.UniqueConstraint(condition=models.Q(('id_sirhus__isnull', False), models.Q(('dir3', ''), _negated=True)), fields=('dir3', 'id_sirhus'), name='unique_together_dir3_id_sirhus')],
            },
        ),
    ]
