# Generated by Django 5.2.4 on 2025-09-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id_organigrama', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_organismo', models.CharField(max_length=144, unique=True)),
                ('dir3', models.CharField(max_length=9, unique=True)),
                ('id_sirhus', models.IntegerField(unique=True)),
                ('categoria', models.CharField(max_length=40)),
                ('ruta', models.CharField(default='', max_length=128)),
                ('depende_de', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organismos_dependientes', to='directorio.organismo')),
            ],
        ),
    ]
