# Generated by Django 6.0.2 on 2026-03-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='dir3',
            field=models.CharField(max_length=9),
        ),
        migrations.AddConstraint(
            model_name='organismo',
            constraint=models.UniqueConstraint(condition=models.Q(('dir3', ''), _negated=True), fields=('dir3',), name='unique_dir3'),
        ),
    ]
