# Generated by Django 5.2.4 on 2025-09-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organismo',
            old_name='id_organigrama',
            new_name='id_organismo',
        ),
    ]
