# Generated by Django 6.0.2 on 2026-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismo',
            name='alias',
            field=models.SlugField(blank=True, default='', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='organismo',
            constraint=models.UniqueConstraint(condition=models.Q(('alias', ''), _negated=True), fields=('alias',), name='unique_alias_if_defined'),
        ),
    ]
