# Generated by Django 6.0.2 on 2026-03-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_alter_organismo_dir3_organismo_unique_dir3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='dir3',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
