# Generated by Django 6.0.2 on 2026-05-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_organismo_alias_organismo_unique_alias_if_defined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id_empresa',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
