# Generated by Django 6.0.2 on 2026-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_alter_organismo_dir3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='id_sirhus',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='organismo',
            constraint=models.UniqueConstraint(condition=models.Q(('id_sirhus__isnull', True), _negated=True), fields=('id_sirhus',), name='unique_id_sirhus'),
        ),
    ]
