# Generated by Django 5.2.4 on 2025-09-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_alter_organismo_depende_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='depende_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organismos_dependientes', to='directorio.organismo'),
        ),
    ]
