# Generated by Django 6.0.2 on 2026-03-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_alter_organismo_id_sirhus_organismo_unique_id_sirhus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='id_sirhus',
            field=models.IntegerField(blank=True),
        ),
    ]
