# Generated by Django 5.2.4 on 2025-09-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0004_alter_organismo_depende_de"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ente",
            fields=[
                (
                    "id_ente",
                    models.SlugField(max_length=12, primary_key=True, serialize=False),
                ),
                (
                    "url_open_data",
                    models.URLField(
                        blank=True, default=None, max_length=384, null=True, unique=True
                    ),
                ),
                (
                    "organismo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ente",
                        to="directorio.organismo",
                    ),
                ),
            ],
        ),
    ]
