# Generated by Django 6.0.2 on 2026-03-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_alter_organismo_id_sirhus'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organismo',
            constraint=models.UniqueConstraint(condition=models.Q(('id_sirhus__isnull', False), models.Q(('dir3', ''), _negated=True)), fields=('dir3', 'id_sirhus'), name='unique_together_dir3_id_sirhus'),
        ),
    ]
