# Generated by Django 5.2.4 on 2025-09-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_ente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organismo',
            options={'ordering': ['nombre_organismo']},
        ),
    ]
