# Generated by Django 5.2.4 on 2025-10-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0006_alter_organismo_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organismo",
            name="url",
            field=models.URLField(blank=True, default=None, max_length=384, null=True),
        ),
    ]
