# Generated by Django 6.0.2 on 2026-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0006_organismo_unique_together_dir3_id_sirhus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=144, unique=True)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('f_alta', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que la empresa se dio de alta')),
                ('f_cambio', models.DateTimeField(auto_now=True, help_text='Fecha de la última modificación de la empresa')),
                ('f_baja', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Empresa externa',
                'verbose_name_plural': 'Empresas externas',
                'db_table': 'dir_empresa',
            },
        ),
    ]
