# Generated by Django 5.2.4 on 2025-10-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0007_organismo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismo',
            name='competencias',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
