# Generated by Django 5.2.4 on 2025-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0008_organismo_competencias"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ente",
            options={"ordering": ["peso", "organismo__nombre_organismo"]},
        ),
        migrations.AddField(
            model_name="ente",
            name="peso",
            field=models.IntegerField(default=100),
        ),
    ]
