# Generated by Django 5.2.8 on 2025-11-27 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0009_alter_ente_options_ente_peso"),
    ]

    operations = [
        migrations.AddField(
            model_name="organismo",
            name="f_alta",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Fecha en la que el organismo se dio de alta",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organismo",
            name="f_baja",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="organismo",
            name="f_cambio",
            field=models.DateTimeField(
                auto_now=True, help_text="Fecha de la última modificación del organismo"
            ),
        ),
    ]
