# Generated by Django 5.2.8 on 2025-12-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0010_organismo_f_alta_organismo_f_baja_organismo_f_cambio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ente",
        ),
    ]
