# Generated by Django 6.0.2 on 2026-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=28, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de evento',
                'verbose_name_plural': 'Tipos de evento',
                'db_table': 'ant_tipo_evento',
            },
        ),
    ]
