# Generated by Django 6.0.2 on 2026-02-27 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antecedentes', '0001_initial'),
        ('sistemas', '0004_eje_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSistema',
            fields=[
                ('id_evento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=2048)),
                ('f_evento', models.DateTimeField(auto_now_add=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='sistemas.sistema')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='antecedentes.tipoevento')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sistemas.usuario')),
            ],
            options={
                'verbose_name': 'Historico de sistema',
                'verbose_name_plural': 'Historicos de sistemas',
                'db_table': 'ant_historico_sistema',
            },
        ),
    ]
