# Generated by Django 6.0.2 on 2026-02-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antecedentes', '0003_historicousuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicosistema',
            old_name='sistema',
            new_name='sujeto',
        ),
    ]
