# Generated by Django 6.0.2 on 2026-03-25 11:58

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NivelEvento",
            fields=[
                (
                    "id_nivel_evento",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("nombre_nivel", models.CharField(max_length=28, unique=True)),
            ],
            options={
                "verbose_name": "Nivel del evento",
                "verbose_name_plural": "Niveles de los eventos",
                "db_table": "obus_nivel_evento",
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id_evento",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sujeto", models.CharField(max_length=32)),
                ("nombre_clase", models.CharField(max_length=48)),
                ("descripcion", models.CharField(max_length=2048)),
                ("momento", models.DateTimeField(auto_now_add=True)),
                ("usuario", models.CharField(max_length=62)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "nivel_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="omnibus.nivelevento",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
                "db_table": "obus_evento",
                "ordering": ["momento"],
            },
        ),
    ]
