# Generated by Django 4.2.26 on 2026-03-18 20:11

from django.db import migrations

NIVELES = {
    'debug': "Mensajes de depuración",
    'info': "Mensajes informativos",
    'insert': "Alta de nuevos datos",
    'update': "Modificación de datos",
    'delete': "Borrado físico de datos",
    'archive': "Borrado lógico o archivado",
    'warning': "Mensajes de aviso",
    'error': "Mensajes de error",
    'panic': "Mensaje de error crítico",
    }


def add_levels(apps, schema_editor):
    NivelEvento = apps.get_model("omnibus", "NivelEvento")
    for id_nivel_evento, nombre_nivel in NIVELES.items():
        try:
            nivel = NivelEvento.objects.get(id_nivel_evento=id_nivel_evento)
            if nivel.nombre_nivel != nombre_nivel:
                nivel.nombre_nivel = nombre_nivel
                nivel.save()
        except NivelEvento.DoesNotExist:
            nivel = NivelEvento(
                id_nivel_evento=id_nivel_evento,
                nombre_nivel=nombre_nivel,
                )
            nivel.save()


def remove_levels(apps, schema_editor):
    NivelEvento = apps.get_model("omnibus", "NivelEvento")
    for nivel in NivelEvento.objects.all():
        if nivel.pk in NIVELES:
            nivel.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('omnibus', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_levels, remove_levels),
    ]
