# Generated by Django 6.0.2 on 2026-05-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omnibus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="nivel_evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventos",
                to="omnibus.nivelevento",
            ),
        ),
    ]
