# Generated by Django 4.2.26 on 2026-03-18 20:11

from django.db import migrations

do_statements = [
    "INSERT OR REPLACE INTO obus_nivel_evento VALUES ('debug', 'Mensajes de depuración');",
    "INSERT OR REPLACE INTO obus_nivel_evento VALUES ('info', 'Mensajes informativos');",
    "INSERT OR REPLACE INTO obus_nivel_evento VALUES ('insert', 'Alta de nuevos datos');",
    "INSERT OR REPLACE INTO obus_nivel_evento VALUES ('update', 'Modificación de datos');",
    "INSERT OR REPLACE INTO obus_nivel_evento VALUES ('delete', 'Borrado físico de datos');",
    "INSERT OR REPLACE INTO obus_nivel_evento VALUES ('archive', 'Borrado lógico o archivado');",
    "INSERT OR REPLACE INTO obus_nivel_evento VALUES ('warning', 'Mensajes de aviso');",
    "INSERT OR REPLACE INTO obus_nivel_evento VALUES ('error', 'Mensajes de error');",
    "INSERT OR REPLACE INTO obus_nivel_evento VALUES ('panic', 'Mensaje de error crítico');",
    ]

undo_statements = [
    "DELETE FROM obus_nivel_evento;",
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('omnibus', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql=do_statements, reverse_sql=undo_statements),
    ]
