# Generated by Django 6.0.2 on 2026-04-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id_backlog', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=512, verbose_name='Título')),
                ('explicacion', models.TextField(blank=True, default=None, null=True, verbose_name='Explicación')),
                ('estimacion', models.SmallIntegerField(choices=[(5, 'Trivial'), (12, 'Fácil'), (30, 'Normal'), (70, 'Complicada'), (150, 'Muy difícil')], default=30, verbose_name='Estimación de la complejidad')),
                ('prioridad', models.SmallIntegerField(choices=[(5, 'Muy baja'), (12, 'Baja'), (30, 'Media'), (70, 'Alta'), (150, 'Crítica')], default=30, verbose_name='Prioridad')),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(auto_now=True)),
                ('f_finalizacion', models.DateTimeField(blank=True, default=None, null=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog', to='sistemas.sistema')),
            ],
            options={
                'verbose_name': 'Backlog',
                'verbose_name_plural': 'Backlogs',
            },
        ),
    ]
