# Generated by Django 6.0.2 on 2026-03-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistemas', '0009_alter_usuario_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id_backlog', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=512, verbose_name='Título')),
                ('explicacion', models.TextField(blank=True, default=None, null=True)),
                ('estimacion', models.SmallIntegerField(choices=[(5, 'Muy pequeña'), (10, 'Pequeña'), (25, 'Mediana'), (50, 'Grande'), (100, 'Muy grande')], default=10)),
                ('prioridad', models.SmallIntegerField(choices=[(5, 'Muy baja'), (15, 'Baja'), (30, 'Media'), (60, 'Alta'), (100, 'Crítica')], default=15)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(auto_now=True)),
                ('f_finalizacion', models.DateTimeField(blank=True, default=None, null=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog', to='sistemas.sistema')),
            ],
            options={
                'verbose_name': 'Backlog',
                'verbose_name_plural': 'Backlogs',
            },
        ),
    ]
