# Generated by Django 6.0.2 on 2026-06-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0001_initial"),
        ("sistemas", "0008_copy_usuarios_data_to_auth_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backlog",
            name="sistema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tareas",
                to="sistemas.sistema",
            ),
        ),
    ]
