# Generated by Django 6.0.2 on 2026-03-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backlog",
            name="estimacion",
            field=models.SmallIntegerField(
                choices=[
                    (5, "Muy pequeña"),
                    (10, "Pequeña"),
                    (25, "Mediana"),
                    (50, "Grande"),
                    (100, "Muy grande"),
                ],
                default=10,
                verbose_name="Estimación",
            ),
        ),
        migrations.AlterField(
            model_name="backlog",
            name="explicacion",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Explicación"
            ),
        ),
        migrations.AlterField(
            model_name="backlog",
            name="prioridad",
            field=models.SmallIntegerField(
                choices=[
                    (5, "Muy baja"),
                    (15, "Baja"),
                    (30, "Media"),
                    (60, "Alta"),
                    (100, "Crítica"),
                ],
                default=15,
                verbose_name="Prioridad",
            ),
        ),
    ]
