# Generated by Django 6.0.2 on 2026-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0002_alter_backlog_estimacion_alter_backlog_explicacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backlog",
            name="estimacion",
            field=models.SmallIntegerField(
                choices=[
                    (5, "Trivial"),
                    (12, "Fácil"),
                    (30, "Normal"),
                    (70, "Complicada"),
                    (150, "Muy difícil"),
                ],
                default=30,
                verbose_name="Estimación de la complejidad",
            ),
        ),
        migrations.AlterField(
            model_name="backlog",
            name="prioridad",
            field=models.SmallIntegerField(
                choices=[
                    (5, "Muy baja"),
                    (12, "Baja"),
                    (30, "Media"),
                    (70, "Alta"),
                    (150, "Crítica"),
                ],
                default=30,
                verbose_name="Prioridad",
            ),
        ),
    ]
