# Generated by Django 6.0.2 on 2026-04-30 09:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directorio', '0001_initial'),
        ('familias', '0001_initial'),
        ('juriscan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id_activo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_activo', models.CharField(max_length=288)),
                ('descripcion', models.TextField()),
                ('es_prioritario', models.BooleanField(default=False)),
                ('georreferenciado', models.BooleanField(default=False)),
                ('datos_personales', models.CharField(choices=[('NO', 'No contiene datos personales'), ('DP', 'Contiene datos personales'), ('XS', 'Contiene datos personales especialmente sensibles')], default='NO', max_length=2)),
                ('f_alta', models.DateTimeField(auto_now_add=True)),
                ('f_cambio', models.DateTimeField(auto_now=True)),
                ('f_baja', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arquetipo',
            fields=[
                ('id_arquetipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('espacio', models.CharField(blank=True, default='', max_length=12)),
                ('funcion', models.CharField(max_length=16)),
                ('descripcion', models.CharField(max_length=740)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['tipo', 'espacio', 'funcion'],
            },
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id_eje', models.SlugField(max_length=1, primary_key=True, serialize=False)),
                ('nombre_eje', models.CharField(max_length=24, unique=True)),
                ('influencia', models.DecimalField(decimal_places=3, default=Decimal('0.200'), max_digits=4, validators=[django.core.validators.DecimalValidator(4, 3), django.core.validators.MaxValueValidator(Decimal('1.0'), message='La influencia debe estar comprendida entre 0.0 y 1.0'), django.core.validators.MinValueValidator(Decimal('0.0'), message='La influencia debe estar comprendida entre 0.0 y 1.0')])),
                ('orden', models.IntegerField(default=0)),
                ('color', models.CharField(default='silver', max_length=16)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_tema', models.CharField(max_length=96)),
                ('transversal', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nombre_tema'],
            },
        ),
        migrations.CreateModel(
            name='TipoDatos',
            fields=[
                ('tipo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=22, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de datos',
                'verbose_name_plural': 'Tipos de datos',
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id_campo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(max_length=288)),
                ('descripcion', models.TextField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='sistemas.activo')),
                ('arquetipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campos', to='sistemas.arquetipo')),
            ],
        ),
        migrations.CreateModel(
            name='Ente',
            fields=[
                ('id_ente', models.SlugField(max_length=12, primary_key=True, serialize=False)),
                ('peso', models.IntegerField(default=100)),
                ('url_open_data', models.URLField(blank=True, default=None, max_length=384, null=True, unique=True)),
                ('organismo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ente', to='directorio.organismo')),
            ],
            options={
                'ordering': ['peso', 'organismo__nombre_organismo'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.BigAutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.CharField(max_length=1024, unique=True)),
                ('orden', models.IntegerField(default=0)),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='sistemas.eje')),
            ],
            options={
                'ordering': ['eje__orden', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id_opcion', models.BigAutoField(primary_key=True, serialize=False)),
                ('texto_opcion', models.CharField(max_length=1024, unique=True)),
                ('valor', models.DecimalField(decimal_places=3, default=Decimal('0.25'), max_digits=4, validators=[django.core.validators.DecimalValidator(4, 3), django.core.validators.MaxValueValidator(Decimal('1.0'), message='El valor de la opción debe estar comprendida entre 0.0 y 1.0'), django.core.validators.MinValueValidator(Decimal('0.0'), message='La valor de la opción debe estar comprendida entre 0.0 y 1.0')])),
                ('orden', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='sistemas.pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_sistema', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público del sistema (UUID)', unique=True)),
                ('nombre_sistema', models.CharField(help_text='Nombre del sistema', max_length=220, unique=True)),
                ('codigo', models.SlugField(help_text='Código identificador del sistema (una sola palabra)', max_length=32, unique=True)),
                ('url', models.URLField(blank=True, default=None, max_length=720, null=True)),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción del sistema')),
                ('finalidad', models.TextField(blank=True, default='', verbose_name='Finalidad del sistema')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('es_corporativo', models.BooleanField(default=False, help_text='Este S.I. es corporativo')),
                ('especial_importancia', models.BooleanField(default=False, help_text='Este S.I. contiene activos de datos de especial importancia')),
                ('icono_height', models.PositiveIntegerField(default=0)),
                ('icono_width', models.PositiveIntegerField(default=0)),
                ('icono', models.ImageField(blank=True, default=None, height_field='icono_height', max_length=512, null=True, upload_to='sistemas/iconos/%Y/', width_field='icono_width')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('archived', models.DateTimeField(blank=True, default=None, null=True)),
                ('es_subsistema_de', models.ForeignKey(blank=True, default=None, help_text='Es un subsistema de otro S.I.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsistemas', to='sistemas.sistema')),
                ('familia', models.ForeignKey(default='UNK', help_text='Indica la familia, si procede', on_delete=django.db.models.deletion.PROTECT, related_name='sistemas', to='familias.familia')),
                ('organismo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sistemas', to='directorio.organismo')),
                ('tema', models.ForeignKey(default='UNK', on_delete=django.db.models.deletion.PROTECT, related_name='sistemas', to='sistemas.tema')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('es_subsistema_de'), descending=True, nulls_first=True), 'nombre_sistema'],
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='sistemas.sistema'),
        ),
        migrations.AddField(
            model_name='arquetipo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemas.tipodatos'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('login', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=384, unique=True)),
                ('nombre', models.CharField(blank=True, default=None, max_length=96, null=True)),
                ('apellidos', models.CharField(blank=True, default=None, max_length=192, null=True)),
                ('f_alta', models.DateTimeField(auto_now_add=True)),
                ('f_cambio', models.DateTimeField(auto_now=True)),
                ('f_baja', models.DateTimeField(blank=True, default=None, null=True)),
                ('empresa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='directorio.empresa')),
                ('organismo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='directorio.organismo')),
            ],
            options={
                'ordering': ['nombre', 'apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.BigAutoField(primary_key=True, serialize=False)),
                ('cometido', models.CharField(choices=[('FUN', 'Responsable funcional'), ('TEC', 'Responsable técnico'), ('PDD', 'Protección de datos'), ('INT', 'Interlocutor')], max_length=3)),
                ('f_alta', models.DateTimeField(auto_now_add=True)),
                ('f_cambio', models.DateTimeField(auto_now=True)),
                ('f_baja', models.DateTimeField(blank=True, default=None, null=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='sistemas.sistema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='sistemas.usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Interlocutor',
            fields=[
                ('id_interlocutor', models.BigAutoField(primary_key=True, serialize=False)),
                ('f_alta', models.DateTimeField(auto_now_add=True)),
                ('f_cambio', models.DateTimeField(auto_now=True)),
                ('f_baja', models.DateTimeField(blank=True, default=None, null=True)),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interlocutores', to='directorio.organismo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interlocutor_de', to='sistemas.usuario')),
            ],
            options={
                'verbose_name': 'Interlocutor',
                'verbose_name_plural': 'Interlocutores',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('f_respuesta', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(default='', max_length=4018)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sistemas.opcion')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sistemas.sistema')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['opcion__pregunta__orden'],
                'unique_together': {('sistema', 'opcion')},
            },
        ),
        migrations.CreateModel(
            name='JuriscanSistema',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('juriscan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='juriscan.juriscan')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_juriscan', to='sistemas.sistema')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sistema', 'juriscan'), name='unq_sistema_juriscan')],
            },
        ),
        migrations.AddConstraint(
            model_name='arquetipo',
            constraint=models.UniqueConstraint(fields=('tipo', 'espacio', 'funcion'), name='arquetipo_clave_natural'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('empresa', None), ('organismo', None), _negated=True), name='empresa_or_organismo_is_mandatory'),
        ),
    ]
