# Generated by Django 6.0.2 on 2026-02-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sistema",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("es_subsistema_de"), descending=True, nulls_first=True
                    ),
                    "nombre_sistema",
                ]
            },
        ),
    ]
