# Generated by Django 5.2.4 on 2025-07-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tema",
            options={"ordering": ["nombre_tema"]},
        ),
        migrations.AddField(
            model_name="tema",
            name="transversal",
            field=models.BooleanField(default=False),
        ),
    ]
