# Generated by Django 6.0.2 on 2026-02-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0002_alter_sistema_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="respuesta",
            name="comentario",
            field=models.CharField(default="", max_length=4018),
        ),
    ]
