# Generated by Django 6.0.2 on 2026-05-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0002_alter_arquetipo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='codigo',
            field=models.SlugField(help_text='Código identificador del sistema (una sola palabra)', max_length=36, unique=True),
        ),
    ]
