# Generated by Django 5.2.3 on 2025-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0002_alter_tema_options_tema_transversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='es_transversal',
            field=models.BooleanField(default=False, help_text='Este sistema de información es horizontal a todos los departamentos.'),
        ),
    ]
