# Generated by Django 5.2.4 on 2025-07-31 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0003_sistema_es_transversal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistema',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='sistema',
            name='es_subsistema_de',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                help_text='Es un subsistema de otro S.I.',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='subsistemas',
                to='sistemas.sistema',
                ),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='es_transversal',
            field=models.BooleanField(default=False, help_text='Este S.I. es horizontal a todos los departamentos.'),
        ),
    ]
