# Generated by Django 5.2.4 on 2025-07-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0003_sistema_es_transversal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sistema",
            options={"ordering": ["nombre"]},
        ),
        migrations.RenameField(
            model_name='sistema',
            old_name='explicacion',
            new_name='proposito',
        ),
    ]
