# Generated by Django 6.0.2 on 2026-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0003_respuesta_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="eje",
            name="color",
            field=models.CharField(default="silver", max_length=16),
        ),
    ]
