# Generated by Django 6.0.2 on 2026-05-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0003_alter_sistema_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistema",
            name="ente",
            field=models.SlugField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
