# Generated by Django 5.2.4 on 2025-07-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0004_alter_sistema_options_sistema_es_subsistema_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='icono',
            field=models.ImageField(blank=True, default=None, height_field='icono_height', max_length=512, null=True, upload_to='sistemas/iconos/%Y/', width_field='icono_width'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='icono_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sistema',
            name='icono_width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
