# Generated by Django 6.0.2 on 2026-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0004_sistema_ente"),
    ]

    operations = [
        migrations.AddField(
            model_name="ente",
            name="ruta",
            field=models.CharField(default="", max_length=128),
        ),
    ]
