# Generated by Django 5.2.4 on 2025-07-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0004_alter_sistema_rename_explicacion_to_proposito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistema",
            name="proposito",
            field=models.TextField(blank=True, default="", verbose_name="Propósito"),
        ),
    ]
