# Generated by Django 5.2.4 on 2025-08-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0005_alter_sistema_proposito"),
        ("sistemas", "0005_sistema_icono_sistema_icono_height_and_more"),
    ]

    operations = []
