# Generated by Django 6.0.2 on 2026-05-19 13:24

from django.db import migrations

SQL_UPDATE_RUTA = """
    UPDATE sistemas_ente e
       SET ruta = (
           SELECT ruta
             FROM directorio_organismo
            WHERE id_organismo = organismo_id
            )
     WHERE ruta = ''
    """

SQL_RESET_RUTA = """
    UPDATE sistemas_ente
       SET ruta = ''
     WHERE ruta <> ''
    """


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0005_ente_ruta"),
    ]

    operations = [
        migrations.RunSQL(SQL_UPDATE_RUTA, SQL_RESET_RUTA),
        ]
