# Generated by Django 6.0.2 on 2026-03-04 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0007_empresa'),
        ('sistemas', '0006_usuario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='organismo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='directorio.organismo'),
        ),
    ]
