# Generated by Django 5.2.4 on 2025-08-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0006_merge_20250826_1051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistema",
            name="descripcion",
            field=models.TextField(max_length=512),
        ),
    ]
