# Generated by Django 6.0.2 on 2026-05-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0006_update_ruta_ente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistema",
            name="codigo",
            field=models.SlugField(
                help_text="Código identificador del sistema (una sola palabra)",
                max_length=36,
                unique=True,
                verbose_name="Nombre Código",
            ),
        ),
        migrations.AlterField(
            model_name="sistema",
            name="nombre_sistema",
            field=models.CharField(
                help_text="Nombre del sistema",
                max_length=220,
                unique=True,
                verbose_name="Nombre del sistema",
            ),
        ),
    ]
