# Generated by Django 6.0.2 on 2026-03-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0007_empresa'),
        ('sistemas', '0007_alter_usuario_organismo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('empresa', None), ('organismo', None), _negated=True), name='empresa_or_organismo_is_mandatory'),
        ),
    ]
