# Generated by Django 5.2.4 on 2025-09-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0007_alter_sistema_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activo",
            fields=[
                ("id_activo", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=288)),
                ("descripcion", models.TextField()),
                ("es_prioritario", models.BooleanField(default=False)),
                ("esta_georeferenciado", models.BooleanField(default=False)),
                (
                    "datos_personales",
                    models.CharField(
                        choices=[
                            ("NO", "No contiene datos personales"),
                            ("DP", "Contiene datos personales"),
                            ("XS", "Contiene datos personales especialmente sensibles"),
                        ],
                        default="NO",
                        max_length=2,
                    ),
                ),
                (
                    "sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activos",
                        to="sistemas.sistema",
                    ),
                ),
            ],
        ),
    ]
