# Generated by Django 6.0.2 on 2026-05-22 18:21

import secrets
import string

from django.db import migrations


def random_password(num_letters=22):
    alphabet = string.ascii_letters + string.digits + '!?*._'
    return ''.join(secrets.choice(alphabet) for _ in range(num_letters))


def create_auth_user(apps, schema_editor):
    Usuario = apps.get_model("sistemas", "Usuario")
    AuthUser = apps.get_model("auth", "User")
    for usuario in Usuario.objects.filter(f_baja=None):
        if AuthUser.objects.filter(username=usuario.login).exists():
            continue
        new_user = AuthUser(
            password=random_password(),
            is_superuser=False,
            is_staff=True,
            is_active=True,
            username=usuario.login,
            first_name=usuario.nombre,
            last_name=usuario.apellidos,
            email=usuario.email,
            date_joined=usuario.f_alta,
            )
        new_user.save()


def undo_create_auth_user(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0007_alter_sistema_codigo_alter_sistema_nombre_sistema"),
    ]

    operations = [
        migrations.RunPython(
            create_auth_user,
            undo_create_auth_user,
            ),
        ]
