# Generated by Django 6.0.2 on 2026-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0008_copy_usuarios_data_to_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='etapa',
            field=models.CharField(choices=[('D', 'En desarrollo'), ('E', 'En explotación'), ('S', 'En proceso de sustitución'), ('X', 'Retirado')], default='E', max_length=1),
        ),
    ]
