# Generated by Django 5.2.4 on 2025-09-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0008_activo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activo",
            old_name="nombre",
            new_name="nombre_activo",
        ),
    ]
