# Generated by Django 6.0.2 on 2026-03-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0008_usuario_empresa_or_organismo_is_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(max_length=96, primary_key=True, serialize=False),
        ),
    ]
