# Generated by Django 6.0.2 on 2026-04-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0009_alter_usuario_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activo",
            old_name="esta_georeferenciado",
            new_name="georeferenciado",
        ),
    ]
