# Generated by Django 5.2.4 on 2025-09-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0009_rename_nombre_activo_nombre_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistema",
            name="responsable_funcional",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="sistema",
            name="responsable_tecnico",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
