# Generated by Django 5.2.4 on 2025-09-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0004_alter_organismo_depende_de"),
        ("sistemas", "0010_sistema_responsable_funcional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistema",
            name="organismo",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sistemas",
                to="directorio.organismo",
            ),
        ),
    ]
