# Generated by Django 6.0.2 on 2026-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0010_rename_esta_georeferenciado_activo_georeferenciado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arquetipo",
            fields=[
                (
                    "id_arquetipo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("int", "Número entero"),
                            ("bool", "Valor booleano"),
                            ("str", "Texto"),
                            ("float", "Número decimal"),
                            ("date", "Fecha"),
                            ("datetime", "Fecga y hora"),
                        ],
                        max_length=8,
                    ),
                ),
                ("espacio", models.CharField(default="", max_length=12)),
                ("funcion", models.CharField(max_length=10)),
                ("descripcion", models.CharField(max_length=740)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo", "espacio", "funcion"),
                        name="arquetipo_clave_natural",
                    )
                ],
            },
        ),
    ]
