# Generated by Django 5.2.4 on 2025-09-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0011_sistema_organismo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistema",
            name="url",
            field=models.URLField(blank=True, default=None, max_length=720, null=True),
        ),
    ]
