# Generated by Django 6.0.2 on 2026-04-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0011_arquetipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquetipo",
            name="espacio",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
    ]
