# Generated by Django 6.0.2 on 2026-04-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0012_alter_arquetipo_espacio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquetipo",
            name="funcion",
            field=models.CharField(max_length=16),
        ),
    ]
