# Generated by Django 5.2.4 on 2025-09-15 11:05

from django.db import migrations


def set_organismo(apps, schema_editor):
    '''Definir el organismo usando el codigo DIR3.
    '''
    Sistema = apps.get_model("sistemas", "Sistema")
    Organismo = apps.get_model("directorio", "Organismo")
    for sistema in Sistema.objects.filter(organismo__isnull=True):
        organismo = Organismo.objects.get(dir3=sistema.dir3_id)
        sistema.organismo = organismo
        sistema.save()

def unset_organismo(apps, schema_editor):
    Sistema = apps.get_model("sistemas", "Sistema")
    for sistema in Sistema.objects.all():
        sistema.organismo = None
        sistema.save()



class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0012_sistema_url"),
    ]

    operations = [
        migrations.RunPython(set_organismo, unset_organismo),
        ]
