# Generated by Django 6.0.2 on 2026-04-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0013_alter_arquetipo_funcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquetipo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("int", "Número entero"),
                    ("float", "Número decimal"),
                    ("bool", "Valor lógico"),
                    ("str", "Texto"),
                    ("date", "Fecha"),
                    ("datetime", "Fecha y hora"),
                ],
                max_length=8,
            ),
        ),
    ]
