# Generated by Django 5.2.4 on 2025-09-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0013_alimentar_codigo_organismo_a_partir_del_dir3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sistema",
            name="dir3_id",
        ),
    ]
