# Generated by Django 6.0.2 on 2026-04-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0014_alter_arquetipo_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDatos",
            fields=[
                (
                    "tipo",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("nombre_tipo", models.CharField(max_length=22, unique=True)),
            ],
        ),
    ]
