# Generated by Django 5.2.4 on 2025-10-02 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0006_alter_organismo_options"),
        ("sistemas", "0014_remove_sistema_dir3_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "login",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=384, unique=True)),
                (
                    "nombre",
                    models.CharField(
                        blank=True, default=None, max_length=96, null=True
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, default=None, max_length=192, null=True
                    ),
                ),
                ("f_alta", models.DateTimeField(auto_now_add=True)),
                ("f_cambio", models.DateTimeField(auto_now=True)),
                ("f_baja", models.DateTimeField(default=None)),
                (
                    "organismo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usurioos",
                        to="directorio.organismo",
                    ),
                ),
            ],
        ),
    ]
