# Generated by Django 5.2.4 on 2025-10-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0015_usuario"),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO sistemas_usuario ("
            "       login,"
            "       email,"
            "       organismo_id,"
            "       f_alta,"
            "       f_cambio,"
            "       f_baja"
            " )"
            " SELECT DISTINCT responsable_funcional,"
            "        responsable_funcional||'@gobiernodecanarias.org',"
            "        organismo_id,"
            "        current_timestamp,"
            "        current_timestamp,"
            "        current_timestamp"
            "   FROM sistemas_sistema"
            "  WHERE responsable_funcional is not null"
            " UNION"
            " SELECT DISTINCT responsable_tecnico,"
            "        responsable_tecnico||'@gobiernodecanarias.org',"
            "        organismo_id,"
            "        current_timestamp,"
            "        current_timestamp,"
            "        current_timestamp"
            "   FROM sistemas_sistema"
            "  WHERE responsable_tecnico is not null"
            ,
            'DELETE FROM sistemas_usuario'
            ),
        ]
