# Generated by Django 6.0.2 on 2026-04-10 20:26

from django.db import migrations

do_statements = [
    "INSERT INTO sistemas_tipodatos (tipo, nombre_tipo) VALUES ('int', 'Número entero');",
    "INSERT INTO sistemas_tipodatos (tipo, nombre_tipo) VALUES ('float', 'Número decimal');",
    "INSERT INTO sistemas_tipodatos (tipo, nombre_tipo) VALUES ('bool', 'Valor lógico');",
    "INSERT INTO sistemas_tipodatos (tipo, nombre_tipo) VALUES ('str', 'Texto');",
    "INSERT INTO sistemas_tipodatos (tipo, nombre_tipo) VALUES ('date', 'Fecha');",
    "INSERT INTO sistemas_tipodatos (tipo, nombre_tipo) VALUES ('datetime', 'Fecha/hora (Timestamp)');",
    ]

undo_statements = [
    "DELETE FROM sistemas_tipo_datos;",
    ]



class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0015_tipodatos"),
    ]

    operations = [
        migrations.RunSQL(
            do_statements,
            undo_statements,
            )
        ]
