# Generated by Django 5.2.4 on 2025-10-02 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0006_alter_organismo_options"),
        ("sistemas", "0016_migrate_usuarios"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="f_baja",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="organismo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usurios",
                to="directorio.organismo",
            ),
        ),
    ]
