# Generated by Django 6.0.2 on 2026-04-10 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0016_default_values_for_tipo_datos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquetipo",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sistemas.tipodatos"
            ),
        ),
    ]
