# Generated by Django 5.2.4 on 2025-10-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0017_alter_usuario_f_baja_alter_usuario_organismo"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE sistemas_usuario SET f_baja = NULL",
            "UPDATE sistemas_usuario SET f_baja = current_timestamp",
            ),
        ]
