# Generated by Django 6.0.2 on 2026-04-10 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0017_alter_arquetipo_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campo",
            fields=[
                ("id_campo", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_campo", models.CharField(max_length=288)),
                ("descripcion", models.TextField()),
                (
                    "activo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campos",
                        to="sistemas.activo",
                    ),
                ),
                (
                    "arquetipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campos",
                        to="sistemas.arquetipo",
                    ),
                ),
            ],
        ),
    ]
