# Generated by Django 5.2.4 on 2025-10-02 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0018_fix_f_baja_usuarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                ("id_perfil", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cometido",
                    models.CharField(
                        choices=[
                            ("FUN", "Responsable funcional"),
                            ("TEC", "Responsable técnico"),
                            ("PDD", "Protección de datos"),
                        ],
                        max_length=3,
                    ),
                ),
                ("f_alta", models.DateTimeField(auto_now_add=True)),
                ("f_cambio", models.DateTimeField(auto_now=True)),
                ("f_baja", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfiles",
                        to="sistemas.sistema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfiles",
                        to="sistemas.usuario",
                    ),
                ),
            ],
        ),
    ]
