# Generated by Django 6.0.2 on 2026-04-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0018_campo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipodatos",
            options={
                "verbose_name": "Tipo de datos",
                "verbose_name_plural": "Tipos de datos",
            },
        ),
    ]
