# Generated by Django 6.0.2 on 2026-04-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0019_alter_tipodatos_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sistema",
            old_name="tiene_especial_importancia",
            new_name="especial_importancia",
        ),
    ]
