# Generated by Django 5.2.4 on 2025-10-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0019_perfil"),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO sistemas_perfil ("
            "       usuario_id,"
            "       cometido,"
            "       sistema_id,"
            "       f_alta,"
            "       f_cambio,"
            "       f_baja"
            "       )"
            " SELECT responsable_funcional,"
            "        'FUN',"
            "        id_sistema,"
            "        current_timestamp,"
            "        current_timestamp,"
            "        NULL"
            "   FROM sistemas_sistema"
            "  where responsable_funcional is not null"
            ,
            "DELETE FROM sistemas_perfil where cometido='FUN'",
            ),
        migrations.RunSQL(
            "INSERT INTO sistemas_perfil ("
            "       usuario_id,"
            "       cometido,"
            "       sistema_id,"
            "       f_alta,"
            "       f_cambio,"
            "       f_baja"
            "       )"
            " SELECT responsable_tecnico,"
            "        'TEC',"
            "        id_sistema,"
            "        current_timestamp,"
            "        current_timestamp,"
            "        NULL"
            "   FROM sistemas_sistema"
            "  where responsable_tecnico is not null"
            ,
            "DELETE FROM sistemas_perfil where cometido='TEC'",
            ),
        ]

