# Generated by Django 6.0.2 on 2026-04-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sistemas",
            "0020_rename_tiene_especial_importancia_sistema_especial_importancia",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="activo",
            old_name="georeferenciado",
            new_name="georreferenciado",
        ),
    ]
