# Generated by Django 5.2.4 on 2025-10-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0020_asigna_usuarios_a_sistemas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sistema",
            name="responsable_funcional",
        ),
        migrations.RemoveField(
            model_name="sistema",
            name="responsable_tecnico",
        ),
    ]
