# Generated by Django 5.2.4 on 2025-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0021_remove_sistema_responsable_funcional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="cometido",
            field=models.CharField(
                choices=[
                    ("FUN", "Responsable funcional"),
                    ("TEC", "Responsable técnico"),
                    ("PDD", "Protección de datos"),
                    ("INT", "Interlocutor"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="sistema",
            name="nombre",
            field=models.CharField(
                help_text="Nombre del sistema", max_length=220, unique=True
            ),
        ),
    ]
