# Generated by Django 6.0.2 on 2026-04-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0021_rename_georeferenciado_activo_georreferenciado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arquetipo",
            options={"ordering": ["tipo", "espacio", "funcion"]},
        ),
        migrations.RenameField(
            model_name="sistema",
            old_name="es_transversal",
            new_name="es_corporativo",
        ),
    ]
