# Generated by Django 5.2.4 on 2025-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0022_alter_perfil_cometido_alter_sistema_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistema",
            name="codigo",
            field=models.CharField(
                help_text="Código identificador del sistema (una sola palabra)",
                max_length=32,
                unique=True,
            ),
        ),
    ]
