# Generated by Django 6.0.2 on 2026-04-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0022_alter_arquetipo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistema",
            name="es_corporativo",
            field=models.BooleanField(
                default=False, help_text="Este S.I. es corporativo"
            ),
        ),
    ]
