# Generated by Django 6.0.2 on 2026-04-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0023_alter_sistema_es_corporativo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sistema",
            old_name="f_alta",
            new_name="created",
        ),
    ]
