# Generated by Django 5.2.4 on 2025-10-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0006_alter_organismo_options"),
        ("sistemas", "0023_alter_sistema_codigo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfil",
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfiles"},
        ),
        migrations.CreateModel(
            name="Interlocutor",
            fields=[
                (
                    "id_interlocutor",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("f_alta", models.DateTimeField(auto_now_add=True)),
                ("f_cambio", models.DateTimeField(auto_now=True)),
                ("f_baja", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "organismo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interlocutores",
                        to="directorio.organismo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interlocutor_de",
                        to="sistemas.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interlocutor",
                "verbose_name_plural": "Interlocutores",
            },
        ),
    ]
