# Generated by Django 6.0.2 on 2026-04-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0024_rename_f_alta_sistema_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sistema",
            old_name="f_cambio",
            new_name="updated",
        ),
    ]
