# Generated by Django 5.2.4 on 2025-10-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0024_alter_perfil_options_interlocutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='Descripción del sistema'),
        ),
    ]
