# Generated by Django 6.0.2 on 2026-04-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0025_rename_f_cambio_sistema_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sistema",
            old_name="f_baja",
            new_name="archived",
        ),
    ]
