# Generated by Django 5.2.4 on 2025-10-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0025_alter_sistema_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='codigo',
            field=models.SlugField(help_text='Código identificador del sistema (una sola palabra)', max_length=32, unique=True),
        ),
    ]
