# Generated by Django 5.2.4 on 2025-10-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0026_alter_sistema_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistema",
            name="tiene_especial_importancia",
            field=models.BooleanField(
                default=False,
                help_text="Este S.I. contiene activos de datos de especial importancia",
            ),
        ),
    ]
