# Generated by Django 6.0.2 on 2026-04-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0026_rename_f_baja_sistema_archived"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familia",
            options={
                "ordering": ["id_familia"],
                "verbose_name": "familia",
                "verbose_name_plural": "familias",
            },
        ),
    ]
