# Generated by Django 5.2.4 on 2025-10-16 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0027_sistema_tiene_especial_importancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='tema',
            field=models.ForeignKey(default='_U', on_delete=django.db.models.deletion.PROTECT, related_name='sistemas', to='sistemas.tema'),
        ),
    ]
