# Generated by Django 6.0.2 on 2026-04-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0027_alter_familia_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="familia",
            table="fam_familia",
        ),
    ]
