# Generated by Django 5.2.4 on 2025-11-03 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0028_alter_sistema_tema"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={"ordering": ["nombre", "apellidos"]},
        ),
        migrations.AlterField(
            model_name="sistema",
            name="tema",
            field=models.ForeignKey(
                default="UNK",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sistemas",
                to="sistemas.tema",
            ),
        ),
    ]
