# Generated by Django 6.0.2 on 2026-04-27 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("familias", "0001_initial"),
        ("sistemas", "0028_alter_familia_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistema",
            name="familia",
            field=models.ForeignKey(
                default="UNK",
                help_text="Indica la familia, si procede",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sistemas",
                to="familias.familia",
            ),
        ),
        migrations.DeleteModel(
            name="Familia",
        ),
    ]
