# Generated by Django 6.0.2 on 2026-04-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0029_alter_sistema_familia_delete_familia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familia',
        ),
    ]
