# Generated by Django 5.2.4 on 2025-11-03 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0029_alter_usuario_options_alter_sistema_tema"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistema",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Identificador público del sistema (UUID4)",
            ),
        ),
    ]
