# Generated by Django 5.2.4 on 2025-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0030_sistema_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción del sistema'),
        ),
    ]
