# Generated by Django 5.2.4 on 2025-11-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0031_alter_sistema_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id_familia",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("nombre_familia", models.CharField(max_length=128)),
            ],
        ),
    ]
