# Generated by Django 5.2.4 on 2025-11-17 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0032_familia"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistema",
            name="familia",
            field=models.ForeignKey(
                default="UNK",
                help_text="Indica la familia, si porcede",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sistemas",
                to="sistemas.familia",
            ),
        ),
    ]
