# Generated by Django 5.2.8 on 2025-11-19 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0033_sistema_familia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familia",
            options={"ordering": ["id_familia"]},
        ),
        migrations.AlterField(
            model_name="sistema",
            name="familia",
            field=models.ForeignKey(
                default="UNK",
                help_text="Indica la familia, si procede",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sistemas",
                to="sistemas.familia",
            ),
        ),
    ]
