# Generated by Django 5.2.8 on 2025-11-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0034_alter_familia_options_alter_sistema_familia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tema",
            name="nombre_tema",
            field=models.CharField(max_length=96),
        ),
    ]
