# Generated by Django 5.2.8 on 2025-11-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0035_alter_tema_nombre_tema"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistema",
            name="observaciones",
            field=models.TextField(
                blank=True, default="", verbose_name="Observaciones"
            ),
        ),
    ]
