# Generated by Django 5.2.8 on 2025-11-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0036_sistema_observaciones"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormaSistema",
            fields=[
                (
                    "id_normativa",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("num_juriscan", models.PositiveIntegerField()),
                (
                    "resumen",
                    models.CharField(
                        blank=True, default=None, max_length=2048, null=True
                    ),
                ),
                ("f_alta", models.DateTimeField(auto_now_add=True)),
                ("f_cambio", models.DateTimeField(auto_now=True)),
                ("f_baja", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normativa",
                        to="sistemas.sistema",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sistema", "num_juriscan"),
                        name="unique_sistema_juriscan",
                    )
                ],
            },
        ),
    ]
