# Generated by Django 5.2.8 on 2025-11-24 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0037_normasistema"),
    ]

    operations = [
        migrations.AddField(
            model_name="activo",
            name="f_alta",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activo",
            name="f_baja",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="activo",
            name="f_cambio",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
