# Generated by Django 5.2.8 on 2025-11-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0039_sistema_f_alta_sistema_f_baja_sistema_f_cambio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sistema",
            options={"ordering": ["nombre_sistema"]},
        ),
        migrations.RenameField(
            model_name="sistema",
            old_name="nombre",
            new_name="nombre_sistema",
        ),
    ]
