# Generated by Django 5.2.8 on 2025-12-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0011_delete_ente"),
        ("sistemas", "0040_alter_sistema_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ente",
            fields=[
                (
                    "id_ente",
                    models.SlugField(max_length=12, primary_key=True, serialize=False),
                ),
                ("peso", models.IntegerField(default=100)),
                (
                    "url_open_data",
                    models.URLField(
                        blank=True, default=None, max_length=384, null=True, unique=True
                    ),
                ),
                (
                    "organismo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ente",
                        to="directorio.organismo",
                    ),
                ),
            ],
            options={
                "ordering": ["peso", "organismo__nombre_organismo"],
            },
        ),
    ]
