# Generated by Django 5.2.8 on 2025-12-01 13:07

from django.db import migrations
from django.db import transaction


ENTES = [
	{
		"id_ente" : "PREGOB",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/presidencia-del-gobierno",
		"organismo_id" : 42091,
		"peso" : 0
	},
	{
		"id_ente" : "PAPJS",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-de-administraciones-publicas",
		"organismo_id" : 42118,
		"peso" : 400
	},
	{
		"id_ente" : "EICA",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-de-economia",
		"organismo_id" : 42104,
		"peso" : 100
	},
	{
		"id_ente" : "OPVM",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-de-obras-publicas",
		"organismo_id" : 42114,
		"peso" : 200
	},
	{
		"id_ente" : "TEE",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/dataset/?organization=consejeria-de-transicion-ecologica-y-energia",
		"organismo_id" : 42159,
		"peso" : 900
	},
	{
		"id_ente" : "TUREMP",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-de-turismo",
		"organismo_id" : 42143,
		"peso" : 700
	},
	{
		"id_ente" : "AGPSA",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-de-agricultura",
		"organismo_id" : 42084,
		"peso" : 1200
	},
	{
		"id_ente" : "BSIJIF",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-de-bienestar-social",
		"organismo_id" : 42165,
		"peso" : 1000
	},
	{
		"id_ente" : "EFPAFD",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-de-educacion",
		"organismo_id" : 42123,
		"peso" : 500
	},
	{
		"id_ente" : "HRUE",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-de-hacienda",
		"organismo_id" : 42086,
		"peso" : 300
	},
	{
		"id_ente" : "ISTAC",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/istac",
		"organismo_id" : 37829,
		"peso" : 350
	},
	{
		"id_ente" : "PTCTA",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-politica-territorial",
		"organismo_id" : 42136,
		"peso" : 600
	},
	{
		"id_ente" : "SAN",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-de-sanidad",
		"organismo_id" : 6547,
		"peso" : 1100
	},
	{
		"id_ente" : "UCIC",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/consejeria-universidades-ciencia-innovacion-cultura",
		"organismo_id" : 42150,
		"peso" : 800
	},
	{
		"id_ente" : "ACIISI",
		"url_open_data" : None,
		"organismo_id" : 42158,
		"peso" : 850
	},
	{
		"id_ente" : "ACPMN",
		"url_open_data" : None,
		"organismo_id" : 41854,
		"peso" : 650
	},
	{
		"id_ente" : "ACCUEE",
		"url_open_data" : None,
		"organismo_id" : 38691,
		"peso" : 550
	},
	{
		"id_ente" : "ATC",
		"url_open_data" : None,
		"organismo_id" : 37815,
		"peso" : 350
	},
	{
		"id_ente" : "ESSSCAN",
		"url_open_data" : None,
		"organismo_id" : 6564,
		"peso" : 1150
	},
	{
		"id_ente" : "ICAVI",
		"url_open_data" : None,
		"organismo_id" : 37152,
		"peso" : 250
	},
	{
		"id_ente" : "ICIA",
		"url_open_data" : None,
		"organismo_id" : 32766,
		"peso" : 1250
	},
	{
		"id_ente" : "ICI",
		"url_open_data" : None,
		"organismo_id" : 25999,
		"peso" : 1050
	},
	{
		"id_ente" : "SCE",
		"url_open_data" : "https://datos.canarias.es/catalogos/general/organization/servicio-canario-de-empleo",
		"organismo_id" : 42149,
		"peso" : 750
	},
	{
		"id_ente" : "SCS",
		"url_open_data" : None,
		"organismo_id" : 6594,
		"peso" : 1150
	}
]


def insert_entes(apps, schema_editor):
    Ente = apps.get_model('sistemas', 'Ente')
    with transaction.atomic():
        for data in ENTES:
            Ente(**data).save()


def undo_insert_entes(apps, schema_editor):
    Ente = apps.get_model('sistemas', 'Ente')
    Ente.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0041_ente"),
        ("directorio", "0011_delete_ente"),
    ]

    operations = [
        migrations.RunPython(insert_entes, undo_insert_entes),
        ]
