# Generated by Django 5.2.8 on 2025-12-03 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0042_recreate_entes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistema",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Identificador público del sistema (UUID4)",
                unique=True,
            ),
        ),
    ]
