# Generated by Django 5.2.8 on 2025-12-04 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0011_delete_ente"),
        ("sistemas", "0043_alter_sistema_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="organismo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="directorio.organismo",
            ),
        ),
    ]
