# Generated by Django 5.2.8 on 2025-12-09 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0044_alter_usuario_organismo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistema",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Identificador público del sistema (UUID)",
                unique=True,
            ),
        ),
    ]
