# Generated by Django 5.2.8 on 2025-12-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0045_alter_sistema_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sistema",
            old_name="uuid",
            new_name="uuid_sistema",
        ),
    ]
