# Generated by Django 6.0.1 on 2026-02-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0046_rename_uuid_sistema_uuid_sistema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistema',
            old_name='proposito',
            new_name='finalidad',
        ),
    ]
