# Generated by Django 6.0.1 on 2026-02-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0047_rename_proposito_sistema_finalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='finalidad',
            field=models.TextField(blank=True, default='', verbose_name='Finalidad del sistema'),
        ),
    ]
