# Generated by Django 6.0.2 on 2026-02-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juriscan", "0002_rename_cheked_juriscan_checked"),
        ("sistemas", "0048_alter_sistema_finalidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="JuriscanSistema",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "juriscan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sistemas",
                        to="juriscan.juriscan",
                    ),
                ),
                (
                    "sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fichas_juriscan",
                        to="sistemas.sistema",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sistema", "juriscan"), name="unq_sistema_juriscan"
                    )
                ],
            },
        ),
    ]
