# Generated by Django 6.0.2 on 2026-02-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0049_juriscansistema"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="normasistema",
            name="unique_sistema_juriscan",
        ),
        migrations.DeleteModel(
            name="NormaSistema",
        ),
    ]
