# Generated by Django 6.0.2 on 2026-02-16 10:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0050_remove_normasistema_unique_sistema_juriscan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eje",
            fields=[
                (
                    "id_eje",
                    models.SlugField(max_length=1, primary_key=True, serialize=False),
                ),
                ("nombre_eje", models.CharField(max_length=24, unique=True)),
                (
                    "influencia",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.200"),
                        max_digits=4,
                        validators=[
                            django.core.validators.DecimalValidator(4, 3),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.0"),
                                message="La influencia debe estar comprendida entre 0.0 y 1.0",
                            ),
                            django.core.validators.MinValueValidator(
                                Decimal("0.0"),
                                message="La influencia debe estar comprendida entre 0.0 y 1.0",
                            ),
                        ],
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
    ]
