# Generated by Django 6.0.2 on 2026-02-16 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0051_eje"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id_pregunta",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("texto_pregunta", models.CharField(max_length=1024, unique=True)),
                ("orden", models.IntegerField(default=0)),
                (
                    "eje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preguntas",
                        to="sistemas.eje",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
    ]
