# Generated by Django 6.0.2 on 2026-02-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0052_pregunta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="id_pregunta",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
