# Generated by Django 6.0.2 on 2026-02-16 11:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0053_alter_pregunta_id_pregunta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opcion",
            fields=[
                ("id_opcion", models.BigAutoField(primary_key=True, serialize=False)),
                ("texto_opcion", models.CharField(max_length=1024, unique=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.25"),
                        max_digits=4,
                        validators=[
                            django.core.validators.DecimalValidator(4, 3),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.0"),
                                message="El valor de la opción debe estar comprendida entre 0.0 y 1.0",
                            ),
                            django.core.validators.MinValueValidator(
                                Decimal("0.0"),
                                message="La valor de la opción debe estar comprendida entre 0.0 y 1.0",
                            ),
                        ],
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.AlterModelOptions(
            name="pregunta",
            options={"ordering": ["eje__orden", "orden"]},
        ),
    ]
