# Generated by Django 6.0.2 on 2026-02-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0054_opcion_alter_pregunta_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcion",
            name="pregunta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opciones",
                to="sistemas.pregunta",
            ),
            preserve_default=False,
        ),
    ]
