# Generated by Django 6.0.2 on 2026-02-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0055_opcion_pregunta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opcion",
            options={
                "ordering": ["orden"],
                "verbose_name": "Opción",
                "verbose_name_plural": "Opciones",
            },
        ),
    ]
