# Generated by Django 6.0.1 on 2026-02-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0056_alter_opcion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('f_respuesta', models.DateTimeField(auto_now_add=True)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sistemas.opcion')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sistemas.sistema')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['opcion__pregunta__orden'],
                'unique_together': {('sistema', 'opcion')},
            },
        ),
    ]
