# Generated by Django 6.0.2 on 2026-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemas", "0057_respuesta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respuesta",
            name="f_respuesta",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
